### ISSUE TITLE
There is no mechanism for stating that you want this to fail if the two files aren't exactly the same

### ISSUE THREAD

**Issue by lemonlion** [LouisBrunner/diff-action#16]
Great Github action, but for my use case I want my two files to fail if they're not exactly the same.  It appears that there is no mode that can fulfill that use case.  I assumed this would work:

```
mode: addtion
tolerance: same
```

...but unfortunately it passes if one of the files has something added to it.

**Comment by LouisBrunner** [comment]
Hi @lemonlion,

I built this action for a specific purpose where addition/removals might be a desired outcome. Somehow, I never thought about doing a more stricter diff! (Not sure how I missed that 🤦)

I can introduce a `mode: strict` (maybe even make it the default to avoid confusion) which could support your use-case?

**Comment by LouisBrunner** [comment]
Now released as `v2.0.0`

**Comment by lemonlion** [comment]
Ah fantastic! Thanks 🙂
