### ISSUE TITLE
Using a single comment per PR

### ISSUE THREAD

**Issue by WyriHaximus** [LouisBrunner/diff-action#21]
Using this action for my GitHub Workflows and Helm Chart to make sure the generated README's are regenerated when PR's are created. Because it doesn't do this it gets rather spammy when iterating over a PR: https://github.com/WyriHaximusNet/helm-charts/pull/125

Would you be interested in a PR adding this functionality?

**Comment by LouisBrunner** [comment]
Hi @WyriHaximus,

We can definitely look into that! (unless you are interested in contributing? 😄)

**Comment by WyriHaximus** [comment]
> We can definitely look into that! (unless you are interested in contributing? 😄)

Good with both, would have to research how to implement this. Did this in two of my own actions, but neither uses JS

**Comment by LouisBrunner** [comment]
If you already have an example I can look at that would be great. I can try to put something together tomorrow.

**Comment by LouisBrunner** [comment]
Thanks for the references! I will release the changes (i.e. the new attribute `sticky_comment: true`) as v2.1.0 soon.

**Comment by WyriHaximus** [comment]
Awesome, and it uses the title to distinguish between multiple comments. Thanks ❤️ !

**Comment by WyriHaximus** [comment]
Thanks again, just set it up on https://github.com/WyriHaximus/github-workflows/pull/53 and https://github.com/WyriHaximusNet/helm-charts/pull/127 👍
