### ISSUE TITLE
A way to not comment when the diff is successful

### ISSUE THREAD

**Issue by WyriHaximus** [LouisBrunner/diff-action#28]
For PR's like https://github.com/WyriHaximusNet/helm-charts/pull/127 I honestly don't care for the passing diffs and am only interested in the failing one(s). It's not a high priority for me; it's just a nice feature that improves the quality of life.

**Comment by LouisBrunner** [comment]
I really like this, will look into it.

**Comment by LouisBrunner** [comment]
Released as v2.2.0, you can now use `notify_issue: failure` to only get a comment on failures.

Thanks again for your suggestions!
